sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start dockerfile"
  - docker build -t docker-react-app -f Dockerfile.dev ./

script:
  - docker run -e CI=ture docker-react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northest-2"
  app: "docker-react-app2"
  env: "Dockerreactapp2"
  bucket_name: elasticbeanstalk-ap-northeast-2-968478777257I
  bucket_path: "docker-react-app2"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
